config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'urls#index'

  resources :urls, only: %i[index create show], param: :url
  get ':short_url', to: 'urls#visit', as: :visit
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
# frozen_string_literal: true

class Click < ApplicationRecord
  belongs_to :url
end

app/models/url.rb
# frozen_string_literal: true

class Url < ApplicationRecord
  validates :original_url, format: URI::regexp(%w[http https])
  validates_presence_of :original_url, :short_url
  validates_uniqueness_of :short_url

  # scope :latest, -> {}
  #
  def generate_url
    Array('A'..'Z').sample(5).join
  end

  def get_dates(data)
    lst = []
    dates = data.group_by{|x| x.strftime("%-d") if x.strftime("%-m") == "#{Time.now.month}" }
    dates.each {|key,val| lst.push([key,val.count])}
    byebug
    lst
  end

  def get_list(data)
    lst = []
    lst2 = data.group_by{|x| x}
    lst2.each {|key,val| lst.push([key,val.count])}
    lst
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

class UrlsController < ApplicationController
  def index
    # recent 10 short urls
    @url = Url.new
    @urls = Url.last(10)
  end

  def create
    data = params[:url]
    @url = Url.new
    @url.original_url = data[:original_url]
    @url.short_url = @url.generate_url
    if @url.valid?
      @url.save
      redirect_to '/', notice: "URL has successfully been added!" and return
    else
      if !@url.errors[:original_url].empty?
        redirect_to '/', notice: "URL is invalid!" and return
      end

      while !@url.errors[:short_url].empty?
        @url.update_attributes(short_url: @url.generate_url)
      end
      redirect_to '/', notice: "URL has successfully been added!"

    end
  end

  def show
    @url = Url.find_by_short_url(params[:url])
    # implement queries
    if @url.present?
      clicks = Click.all.where(url_id: @url.id).pluck(:created_at)
      @daily_clicks = @url.get_dates(clicks)
      browsers = Click.all.where(url_id: @url.id).pluck(:browser)
      @browsers_clicks = @url.get_list(browsers)
      platform = Click.all.where(url_id: @url.id).pluck(:platform)
      @platform_clicks = @url.get_list(platform)
      byebug
    else
      render file: "#{Rails.root}/public/404"
    end
  end

  def visit
    @url = Url.find_by_short_url(params[:short_url])
    if @url.present?
      @url.update_attributes(clicks_count: @url.clicks_count+1)
      Click.create(browser: browser.name, platform: browser.platform.name, url_id: @url.id)
      redirect_to @url.original_url and return
    else
      render file: "#{Rails.root}/public/404"
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo">HeyURL!</a>
      </div>
    </nav>
    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/urls/index.html.erb
<% if flash[:notice] %>
  <div class="card-panel notice deep-orange"><%= flash[:notice] %></div>
<% end %>
<div class="row">
  <div class="col m12">
    <%= form_for @url do |f| %>
      <div class="card">
        <div class="card-content">
          <div class="row">
            <div class="col m8 offset-m2 center-align">
              <span class="card-title">Create a new short URL</span>
            </div>
          </div>
          <div class="row">
            <div class="col m6 offset-m2">
              <%= f.text_field :original_url, class: 'validate form-control', placeholder: 'Your original URL here' %>
            </div>
            <div class="col m2">
              <button type="submit" class="waves-effect waves-light btn">Shorten URL</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="table highlight">
  <thead>
    <tr>
      <th scope="col">Short URL</th>
      <th scope="col">Original URL</th>
      <th scope="col">Created</th>
      <th scope="col">Clicks Count</th>
      <th scope="col">Stats</th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <th scope="row"><a href="http://127.0.0.1:3000/<%= url.short_url %>">http://127.0.0.1:3000/<%= url.short_url %></a></th>
        <td><a href="<%= url.original_url %>"><%= url.original_url.truncate(50) %></a></td>
        <td><%= url.created_at.strftime("%b %-d, %Y") %></td>
        <td><%= url.clicks_count %></td>
        <td>
          <a href="<%= url_path(url.short_url) %>">
            <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
              <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
            </svg>
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urls/show.html.erb
<div class="row">
  <div class="col s12">
    <ul class="card-panel collection with-header">
      <li class="collection-header">
        <h4>
          Stats for <%= visit_url(@url.short_url) %>
        </h4>
      </li>
      <li class="collection-item">Created <%= @url.created_at.strftime('%b %d, %Y') %></li>
      <li class="collection-item">
        Original URL: <%= link_to @url.original_url %>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div id="total-clicks-chart"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <div class="card-panel">
      <div id="platforms-chart"></div>
    </div>
  </div>

  <div class="col s6">
    <div class="card-panel">
      <div id="browsers-chart"></div>
    </div>
  </div>
</div>

<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  function drawTotalClicksChart() {
    var data = google.visualization.arrayToDataTable([
      ['day', 'clicks'],
    ].concat(<%= raw @daily_clicks %>));

    var options = {
      title: 'total clicks',
      haxis: {
        title: 'day of month'
      },
      vaxis: {
        title: 'clicks'
      }
    };

    var chart = new google.visualization.AreaChart(
      document.getElementById('total-clicks-chart')
    );
    chart.draw(data, options);
  }

  function drawBrowsersChart() {
    var data = google.visualization.arrayToDataTable([
      ['browser', 'clicks'],
    ].concat(<%= raw @browsers_clicks %>));

    var options = {
      title: 'Browsers'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('browsers-chart')
    );
    chart.draw(data, options);
  }

  function drawPlatformsChart() {
    var data = google.visualization.arrayToDataTable([
      ['platform', 'clicks'],
    ].concat(<%= raw @platform_clicks %>));

    var options = {
      title: 'Platform'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('platforms-chart')
    );
    chart.draw(data, options);
  }

  function drawCharts() {
    drawTotalClicksChart();
    drawBrowsersChart();
    drawPlatformsChart();
  }
 </script>